### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#10] opened 2024-10-10 06:30 UTC
# Description
I'm raising a concern regarding the development of the 'About' page for Notesphere. The current content could benefit from further expansion and refinement to clearly articulate the platform's features and purpose. The objective should be to convey the core value propositions—such as seamless organization, user-friendly interface, and productivity enhancement—while ensuring the page engages visitors with compelling visuals and a concise narrative. 

**Current about page**
![about](https://github.com/user-attachments/assets/e96d257c-952d-469e-b72c-b1dfefb17bda)

**Comment by swarupn17** [comment] 2024-10-10 06:36
Hey @shubhankertiwari8 I can do it please assign this task to me.
Thanks !

**Comment by shubhankertiwari8** [comment] 2024-10-10 10:22
@VishalMinj issue assigned to you respond to confirm

**Comment by VishalMinj** [comment] 2024-10-10 10:42
Okay I'll start working on it

**Comment by VishalMinj** [comment] 2024-10-10 10:50
@shubhankertiwari8  nodemon server.js is not working. Tried running from both root and backend dir

![image](https://github.com/user-attachments/assets/55c86934-bb88-4778-8b2e-df13b5c350a9)

**Comment by VishalMinj** [comment] 2024-10-10 12:50
hey @shubhankertiwari8!
Can you share some context info on what would you wanna convey in the about page.
Also, I went thorough your code base and seems like you're using  mongoDB in your setup.
Since I've no experience with it and the issue is to address the frontend, can you please share some screen shots of the pages behind signup & login

**Comment by shubhankertiwari8** [comment] 2024-10-10 12:58
@VishalMinj Looks like you have not read Readme carefully first of all setup node.js and mongoDB in your system and read Readme to get an idea of project and make an about page regarding that

**Comment by VishalMinj** [comment] 2024-10-10 14:25
Just setup mongodb.
I ran node index.js for backend, nodemon server.js didnt work for me

These are the pages right? Hope ain't missing anything this time.

Also am I allowed to use raw css for styling instead of tailwind

![image](https://github.com/user-attachments/assets/b4d80ec1-9310-45ce-9795-30d70e537b65)
![image](https://github.com/user-attachments/assets/a7499a83-697d-44f5-9161-a01696b24cc0)

**Comment by VishalMinj** [comment] 2024-10-10 17:57
Hello @shubhankertiwari8,
here's the draft for about page please review and provide feedback

![image](https://github.com/user-attachments/assets/5fa86336-1e18-42bd-b3dc-c2dfc8b67659)
![image](https://github.com/user-attachments/assets/cbb72f32-c835-499c-97a3-c4203e2aa81c)

**Comment by shubhankertiwari8** [comment] 2024-10-10 18:07
good

**Comment by VishalMinj** [comment] 2024-10-10 18:10
should I make the pr?

**Closed as completed** 2024-10-11 04:28 UTC
Labels: shubhankertiwari8, hacktoberfest, mnnit, contrihub, very-easy, 5
