### ISSUE TITLE
Implement Admin Login/Registration and Feedback Management System

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#15] opened 2024-10-11 05:23 UTC
# Description

We need to create a secure admin login/registration page for Notesphere. This page should only be accessible via a manually entered route (i.e., not accessible through navigation links or UI components to ensure heightened security). The design of the login page should align with the current aesthetic of Notesphere while being distinct enough to indicate it’s for admin access.

Upon successful login, the admin should gain access to a hidden "Dashboard" link in the navigation bar, appearing beside the "About" section. This page will display all feedback submitted by non-admin users, organized in reverse chronological order (newest feedback first).

Admins should not have access to the main homepage used by non-admin users. This functionality is essential for maintaining administrative control while ensuring regular users have a distinct experience.

- Requirements:

- A dedicated admin login/register page only accessible through a direct route.
- Admin-exclusive "Dashboard" page on the navbar displaying user feedback.
- Sorted feedback by date (most recent first).
- Admin restricted from accessing the main user homepage.
- All frontend changes in alignment with current look of Notesphere but not a copy.

**Comment by shubhankertiwari8** [comment] 2024-10-11 10:20
@Manish-Sharma26 issue assigned to you comment to confirm

**Comment by Manish-Sharma26** [comment] 2024-10-11 10:22
Thanks for assigning me. 
I will start working on the issue

**Comment by Manish-Sharma26** [comment] 2024-10-13 06:42
Below is the video of admin login

https://github.com/user-attachments/assets/4b5285ce-d137-471b-91f6-4b45f50e2c60
Added two additional features : Search bar and Charts
admin login accessed through admin-login, dashboard access, no home link access
And current admin can only create more admins and for admin signup here is the video
https://github.com/user-attachments/assets/83a27fee-aa42-4756-b8b4-b9194eaf0df3
Please review it.

**Comment by shubhankertiwari8** [comment] 2024-10-13 07:00
@Manish-Sharma26  please explain what is the use of charts here and also search feature should be implemented on basis of tags

**Comment by Manish-Sharma26** [comment] 2024-10-13 07:04
Charts can be used to get an idea which user has contributed how much to the feedback and also display different tags and how many feedbacks corresponds to a particular tag

**Comment by Manish-Sharma26** [comment] 2024-10-13 07:07
Implemented the Search functionality on the basis of tag , anything else is to be done?

https://github.com/user-attachments/assets/e7e008cf-c3b2-4c0f-81b6-f661ae10b286

**Comment by Manish-Sharma26** [comment] 2024-10-13 07:50
So, can i create the pr?

**Comment by Manish-Sharma26** [comment] 2024-10-16 06:21
@shubhankertiwari8 i have created the pr, please review it and I couldn't submit it on contrihub website as the website was not working.

**Comment by shubhankertiwari8** [comment] 2024-10-16 06:27
@Manish-Sharma26  its running right now try again

**Comment by Manish-Sharma26** [comment] 2024-10-16 06:30
But now the time is over but i created the pr before time and now the issue is not listed in my currently active issue. 
So what to do now?

**Comment by shubhankertiwari8** [comment] 2024-10-16 06:31
@Manish-Sharma26 create a pr request again then

**Comment by Manish-Sharma26** [comment] 2024-10-16 06:33
I have already created a pr request 
Link:
https://github.com/ContriHUB/NoteSphere/pull/17

**Comment by shubhankertiwari8** [comment] 2024-10-16 06:42
@Manish-Sharma26 On website its running

**Comment by Manish-Sharma26** [comment] 2024-10-16 06:50
I have been assigned this issue on 11 oct around 3 40 pm and i made the pr on 13th oct around 3 pm but couldn't submit the pr link on contrihub as website was not working at that time, and now when website is functioning the issue is not in my currently active issue due to which I have no option to submit pr link 
![Screenshot_2024-10-16-12-15-58-940_com android chrome](https://github.com/user-attachments/assets/71ed70f8-6ce4-4b8d-8905-e657d2a21b37)
![Screenshot_2024-10-16-12-16-04-715_com android chrome](https://github.com/user-attachments/assets/5b578401-c0dd-4375-87dc-3bb650d69da8)

**Comment by shubhankertiwari8** [comment] 2024-10-16 06:59
@Manish-Sharma26 can you create a PR request for the issue again or not. Because if you dont get issue reassigned you cant make a PR verification request on portal and wont be rewarded points

**Comment by Manish-Sharma26** [comment] 2024-10-16 07:45
Now when I again request issue assignment, then it doesn't happens. 
![Screenshot_2024-10-16-13-07-38-939_com android chrome](https://github.com/user-attachments/assets/180b6358-9f20-42ca-91d2-c7746dde611a)
And to create a pull request again for the issue, I have to do some changes again in the code.
Moreover this message also came in the discord
![Screenshot_2024-10-16-13-13-59-091_com discord](https://github.com/user-attachments/assets/443546c3-dfbd-4b50-a42a-026b958432ab)
So if the pr is merged, I can ask abhishek sir for the points

**Comment by Manish-Sharma26** [comment] 2024-10-16 13:19
I have requested issue assignment again, please assign me so tha I can submit the pr 
![Screenshot_2024-10-16-18-47-49-563_com android chrome](https://github.com/user-attachments/assets/8433f1a3-9a14-40a2-9787-9e0db7d50758)

**Comment by shubhankertiwari8** [comment] 2024-10-16 14:27
@Manish-Sharma26 When the admin enters admin-login window or register window the buttons on navbar which allow register or login for user should be disabled

**Comment by Manish-Sharma26** [comment] 2024-10-16 16:31
Removed the buttons.

**Closed as completed** 2024-10-16 16:34 UTC
Labels: medium, shubhankertiwari8, 20, hacktoberfest, mnnit, contrihub
